### PR TITLE
all the commits

### PR DESCRIPTION
**Pull request by camzillajs101**
@rickyc @erinl1 this should work. I committed everything (except the readme) on the homework branch.

### CODE REVIEW

**Review by rickyc — CHANGES_REQUESTED** [review]
Too many files in the commit! `master` should have the initial `rails new` files. /cc @erinl1

**Comment by camzillajs101** [comment]
I had already completed the homework before I submitted the pull request or created a new branch, so I'd have to redo all the files I modified. I can do that if you'd like me to?

**Comment by rickyc** [comment]
Oh! This is for the first homework, okay, that's fine. Merge it into master.

**Review by rickyc — APPROVED** [review]
LGTM! Looks good to me. Merge it!

**Pull request merged**
